// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1beta2 "github.com/bborbe/strimzi/k8s/apis/kafka.strimzi.io/v1beta2"
	kafkastrimziiov1beta2 "github.com/bborbe/strimzi/k8s/client/applyconfiguration/kafka.strimzi.io/v1beta2"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=kafka, Version=v1beta2
	case v1beta2.SchemeGroupVersion.WithKind("KafkaTopic"):
		return &kafkastrimziiov1beta2.KafkaTopicApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("KafkaTopicSpec"):
		return &kafkastrimziiov1beta2.KafkaTopicSpecApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("KafkaTopicStatus"):
		return &kafkastrimziiov1beta2.KafkaTopicStatusApplyConfiguration{}
	case v1beta2.SchemeGroupVersion.WithKind("KafkaTopicStatusConditionsElem"):
		return &kafkastrimziiov1beta2.KafkaTopicStatusConditionsElemApplyConfiguration{}

	}
	return nil
}
