// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

// KafkaTopicListerExpansion allows custom methods to be added to
// KafkaTopicLister.
type KafkaTopicListerExpansion interface{}

// KafkaTopicNamespaceListerExpansion allows custom methods to be added to
// KafkaTopicNamespaceLister.
type KafkaTopicNamespaceListerExpansion interface{}
