// Copyright (c) 2025 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

// KafkaTopicListerExpansion allows custom methods to be added to
// KafkaTopicLister.
type KafkaTopicListerExpansion interface{}

// KafkaTopicNamespaceListerExpansion allows custom methods to be added to
// KafkaTopicNamespaceLister.
type KafkaTopicNamespaceListerExpansion interface{}
