// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/strimzi"
	"github.com/bborbe/strimzi/k8s/client/clientset/versioned/typed/kafka.strimzi.io/v1beta2"
	"k8s.io/client-go/rest"
)

type KafkaV1beta2Interface struct {
	KafkaTopicsStub        func(string) v1beta2.KafkaTopicInterface
	kafkaTopicsMutex       sync.RWMutex
	kafkaTopicsArgsForCall []struct {
		arg1 string
	}
	kafkaTopicsReturns struct {
		result1 v1beta2.KafkaTopicInterface
	}
	kafkaTopicsReturnsOnCall map[int]struct {
		result1 v1beta2.KafkaTopicInterface
	}
	RESTClientStub        func() rest.Interface
	rESTClientMutex       sync.RWMutex
	rESTClientArgsForCall []struct {
	}
	rESTClientReturns struct {
		result1 rest.Interface
	}
	rESTClientReturnsOnCall map[int]struct {
		result1 rest.Interface
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KafkaV1beta2Interface) KafkaTopics(arg1 string) v1beta2.KafkaTopicInterface {
	fake.kafkaTopicsMutex.Lock()
	ret, specificReturn := fake.kafkaTopicsReturnsOnCall[len(fake.kafkaTopicsArgsForCall)]
	fake.kafkaTopicsArgsForCall = append(fake.kafkaTopicsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.KafkaTopicsStub
	fakeReturns := fake.kafkaTopicsReturns
	fake.recordInvocation("KafkaTopics", []interface{}{arg1})
	fake.kafkaTopicsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaV1beta2Interface) KafkaTopicsCallCount() int {
	fake.kafkaTopicsMutex.RLock()
	defer fake.kafkaTopicsMutex.RUnlock()
	return len(fake.kafkaTopicsArgsForCall)
}

func (fake *KafkaV1beta2Interface) KafkaTopicsCalls(stub func(string) v1beta2.KafkaTopicInterface) {
	fake.kafkaTopicsMutex.Lock()
	defer fake.kafkaTopicsMutex.Unlock()
	fake.KafkaTopicsStub = stub
}

func (fake *KafkaV1beta2Interface) KafkaTopicsArgsForCall(i int) string {
	fake.kafkaTopicsMutex.RLock()
	defer fake.kafkaTopicsMutex.RUnlock()
	argsForCall := fake.kafkaTopicsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *KafkaV1beta2Interface) KafkaTopicsReturns(result1 v1beta2.KafkaTopicInterface) {
	fake.kafkaTopicsMutex.Lock()
	defer fake.kafkaTopicsMutex.Unlock()
	fake.KafkaTopicsStub = nil
	fake.kafkaTopicsReturns = struct {
		result1 v1beta2.KafkaTopicInterface
	}{result1}
}

func (fake *KafkaV1beta2Interface) KafkaTopicsReturnsOnCall(i int, result1 v1beta2.KafkaTopicInterface) {
	fake.kafkaTopicsMutex.Lock()
	defer fake.kafkaTopicsMutex.Unlock()
	fake.KafkaTopicsStub = nil
	if fake.kafkaTopicsReturnsOnCall == nil {
		fake.kafkaTopicsReturnsOnCall = make(map[int]struct {
			result1 v1beta2.KafkaTopicInterface
		})
	}
	fake.kafkaTopicsReturnsOnCall[i] = struct {
		result1 v1beta2.KafkaTopicInterface
	}{result1}
}

func (fake *KafkaV1beta2Interface) RESTClient() rest.Interface {
	fake.rESTClientMutex.Lock()
	ret, specificReturn := fake.rESTClientReturnsOnCall[len(fake.rESTClientArgsForCall)]
	fake.rESTClientArgsForCall = append(fake.rESTClientArgsForCall, struct {
	}{})
	stub := fake.RESTClientStub
	fakeReturns := fake.rESTClientReturns
	fake.recordInvocation("RESTClient", []interface{}{})
	fake.rESTClientMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaV1beta2Interface) RESTClientCallCount() int {
	fake.rESTClientMutex.RLock()
	defer fake.rESTClientMutex.RUnlock()
	return len(fake.rESTClientArgsForCall)
}

func (fake *KafkaV1beta2Interface) RESTClientCalls(stub func() rest.Interface) {
	fake.rESTClientMutex.Lock()
	defer fake.rESTClientMutex.Unlock()
	fake.RESTClientStub = stub
}

func (fake *KafkaV1beta2Interface) RESTClientReturns(result1 rest.Interface) {
	fake.rESTClientMutex.Lock()
	defer fake.rESTClientMutex.Unlock()
	fake.RESTClientStub = nil
	fake.rESTClientReturns = struct {
		result1 rest.Interface
	}{result1}
}

func (fake *KafkaV1beta2Interface) RESTClientReturnsOnCall(i int, result1 rest.Interface) {
	fake.rESTClientMutex.Lock()
	defer fake.rESTClientMutex.Unlock()
	fake.RESTClientStub = nil
	if fake.rESTClientReturnsOnCall == nil {
		fake.rESTClientReturnsOnCall = make(map[int]struct {
			result1 rest.Interface
		})
	}
	fake.rESTClientReturnsOnCall[i] = struct {
		result1 rest.Interface
	}{result1}
}

func (fake *KafkaV1beta2Interface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KafkaV1beta2Interface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ strimzi.KafkaV1beta2Interface = new(KafkaV1beta2Interface)
