// Code generated by informer-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	time "time"

	kafkastrimziiov1beta2 "github.com/bborbe/strimzi/k8s/apis/kafka.strimzi.io/v1beta2"
	versioned "github.com/bborbe/strimzi/k8s/client/clientset/versioned"
	internalinterfaces "github.com/bborbe/strimzi/k8s/client/informers/externalversions/internalinterfaces"
	v1beta2 "github.com/bborbe/strimzi/k8s/client/listers/kafka.strimzi.io/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaTopicInformer provides access to a shared informer and lister for
// KafkaTopics.
type KafkaTopicInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta2.KafkaTopicLister
}

type kafkaTopicInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKafkaTopicInformer constructs a new informer for KafkaTopic type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKafkaTopicInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKafkaTopicInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKafkaTopicInformer constructs a new informer for KafkaTopic type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKafkaTopicInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KafkaV1beta2().KafkaTopics(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KafkaV1beta2().KafkaTopics(namespace).Watch(context.TODO(), options)
			},
		},
		&kafkastrimziiov1beta2.KafkaTopic{},
		resyncPeriod,
		indexers,
	)
}

func (f *kafkaTopicInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKafkaTopicInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kafkaTopicInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kafkastrimziiov1beta2.KafkaTopic{}, f.defaultInformer)
}

func (f *kafkaTopicInformer) Lister() v1beta2.KafkaTopicLister {
	return v1beta2.NewKafkaTopicLister(f.Informer().GetIndexer())
}
